parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments', 'container.service_subscriber']
        calls:
            -   method: setContainer
                arguments: ['@Psr\Container\ContainerInterface']

    App\Repository\:
        resource: '../src/Repository'
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
